### ISSUE TITLE
Please create a GitHub issue template.

### ISSUE THREAD

**Issue by kwl3434** [ksmabcd135/GreenLunch#1]
Hello
The title says it all.
ex) https://shinsunyoung.tistory.com/35

**Comment by ksmabcd135** [comment]
thanks bro . i created issue template.

**Comment by kwl3434** [comment]
Oh bro, thank you for the feature template.
I'd like a bug template, please.

**Comment by ksmabcd135** [comment]
hey bro.
i create bug template too.
hope you check again for me

**Comment by kwl3434** [comment]
Thank you for your quick response. brooooooo
